# Site settings
title: Booker Blog
header-img: img/home-bg.jpg
email: blog@ronanmurray.ie
copyright_name: Ronan Murray
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "" #"/startbootstrap-clean-blog-jekyll"
url: "" #"http://yourdomain.com"
#twitter_username: ronanmu
#github_username:  ronanmu
#facebook_username:  StartBootstrap
email_username:  blog@ronanmurray.ie
timezone: Europe/Dublin

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
